// <auto-generated />
using System;
using Dent1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dent1.Data.Migrations
{
    [DbContext(typeof(DentContext))]
    [Migration("20260327064205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dent1.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rishi Alluri",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Priya Sharma",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Amit Patel",
                            Phone = "9123456789"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sneha Reddy",
                            Phone = "9988776655"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 2, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vikram Singh",
                            Phone = "9123456789"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ananya Gupta",
                            Phone = "9112233445"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 2, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Rajesh Kumar",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Meena Iyer",
                            Phone = "9556677889"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0009-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Suresh Nair",
                            Phone = "9445566778"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0010-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 3, 15, 9, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Deepa Menon",
                            Phone = "9334455667"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
