// <auto-generated />
using System;
using Dent1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dent1.Data.Migrations
{
    [DbContext(typeof(DentContext))]
    [Migration("20260402101935_FixSeededPasswordHashAlgorithm")]
    partial class FixSeededPasswordHashAlgorithm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dent1.Data.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Dent1.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rishi Alluri",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Priya Sharma",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Amit Patel",
                            Phone = "9123456789"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sneha Reddy",
                            Phone = "9988776655"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 2, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vikram Singh",
                            Phone = "9123456789"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ananya Gupta",
                            Phone = "9112233445"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 2, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Rajesh Kumar",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Meena Iyer",
                            Phone = "9556677889"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0009-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Suresh Nair",
                            Phone = "9445566778"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0010-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 3, 15, 9, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Deepa Menon",
                            Phone = "9334455667"
                        });
                });

            modelBuilder.Entity("Dent1.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("RefreshTokenCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1c2d3e4-1001-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "arjun.rao@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dr. Arjun Rao",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000001",
                            Role = "Doctor",
                            Username = "arjun.rao"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-1002-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kavya.iyer@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dr. Kavya Iyer",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000002",
                            Role = "Doctor",
                            Username = "kavya.iyer"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-2001-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rohan.patient@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Patient Rohan",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000003",
                            Role = "Patient",
                            Username = "rohan.patient"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-2002-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "meera.patient@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Patient Meera",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000004",
                            Role = "Patient",
                            Username = "meera.patient"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-3001-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nikhil.reception@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Receptionist Nikhil",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000005",
                            Role = "Receptionist",
                            Username = "nikhil.reception"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-3002-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sana.reception@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Receptionist Sana",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000006",
                            Role = "Receptionist",
                            Username = "sana.reception"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-4001-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vivek.assistant@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Assistant Vivek",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000007",
                            Role = "Assistant",
                            Username = "vivek.assistant"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-4002-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "neha.assistant@dent1.local",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Assistant Neha",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000008",
                            Role = "Assistant",
                            Username = "neha.assistant"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-5001-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pranav.admin@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin Pranav",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000009",
                            Role = "Admin",
                            Username = "pranav.admin"
                        },
                        new
                        {
                            Id = new Guid("b1c2d3e4-5002-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 3, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anika.admin@dent1.local",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin Anika",
                            PasswordHash = "100000.JT5VEhzJuyrmVT1JUfTzTg==.MIegasu+/slhGIJg+rHKzOvomQCZZPWMRU1+vj0STaQ=",
                            PhoneNumber = "9000000010",
                            Role = "Admin",
                            Username = "anika.admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
