// <auto-generated />
using System;
using Dent1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dent1.Data.Migrations
{
    [DbContext(typeof(DentContext))]
    partial class DentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dent1.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rishi Alluri",
                            Phone = "9876543210",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Priya Sharma",
                            Phone = "9876543210",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Amit Patel",
                            Phone = "9123456789",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0004-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 2, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sneha Reddy",
                            Phone = "9988776655",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0005-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 2, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Vikram Singh",
                            Phone = "9123456789",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0006-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 2, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ananya Gupta",
                            Phone = "9112233445",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0007-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 2, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Rajesh Kumar",
                            Phone = "9876543210",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0008-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Meena Iyer",
                            Phone = "9556677889",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0009-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 3, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Suresh Nair",
                            Phone = "9445566778",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0010-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 3, 15, 9, 30, 0, 0, DateTimeKind.Utc),
                            Name = "Deepa Menon",
                            Phone = "9334455667",
                            TenantId = new Guid("b1b2c3d4-0001-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Dent1.Data.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0001-0000-0000-000000000001"),
                            Code = "patient.read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Patient",
                            Name = "Read Patients"
                        },
                        new
                        {
                            Id = new Guid("20000000-0002-0000-0000-000000000001"),
                            Code = "patient.create",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Patient",
                            Name = "Create Patient"
                        },
                        new
                        {
                            Id = new Guid("20000000-0003-0000-0000-000000000001"),
                            Code = "patient.update",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Patient",
                            Name = "Update Patient"
                        },
                        new
                        {
                            Id = new Guid("20000000-0004-0000-0000-000000000001"),
                            Code = "appointment.read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Appointment",
                            Name = "Read Appointments"
                        },
                        new
                        {
                            Id = new Guid("20000000-0005-0000-0000-000000000001"),
                            Code = "appointment.create",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Appointment",
                            Name = "Create Appointment"
                        },
                        new
                        {
                            Id = new Guid("20000000-0006-0000-0000-000000000001"),
                            Code = "appointment.update",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Appointment",
                            Name = "Update Appointment"
                        },
                        new
                        {
                            Id = new Guid("20000000-0007-0000-0000-000000000001"),
                            Code = "prescription.read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Prescription",
                            Name = "Read Prescriptions"
                        },
                        new
                        {
                            Id = new Guid("20000000-0008-0000-0000-000000000001"),
                            Code = "prescription.create",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "Prescription",
                            Name = "Create Prescription"
                        },
                        new
                        {
                            Id = new Guid("20000000-0009-0000-0000-000000000001"),
                            Code = "user.read",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "User",
                            Name = "Read Users"
                        },
                        new
                        {
                            Id = new Guid("20000000-0010-0000-0000-000000000001"),
                            Code = "user.manage",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Module = "User",
                            Name = "Manage Users"
                        });
                });

            modelBuilder.Entity("Dent1.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "TenantId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Dent1.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0001-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0002-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dental practitioner",
                            IsActive = true,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = new Guid("10000000-0003-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Front desk staff",
                            IsActive = true,
                            Name = "Receptionist"
                        },
                        new
                        {
                            Id = new Guid("10000000-0004-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dental assistant",
                            IsActive = true,
                            Name = "Assistant"
                        },
                        new
                        {
                            Id = new Guid("10000000-0005-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Patient user",
                            IsActive = true,
                            Name = "Patient"
                        });
                });

            modelBuilder.Entity("Dent1.Data.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0002-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0003-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0004-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0005-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0006-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0007-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0008-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0009-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0001-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0010-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0002-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0002-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0004-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0002-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0006-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0002-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0008-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0003-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0003-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0002-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0003-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0004-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0003-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0005-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0004-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0001-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0004-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0004-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0005-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0004-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Dent1.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Default Clinic"
                        });
                });

            modelBuilder.Entity("Dent1.Data.Entities.TenantRolePermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RoleId", "PermissionId", "Effect")
                        .IsUnique();

                    b.ToTable("TenantRolePermissionOverrides");
                });

            modelBuilder.Entity("Dent1.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("RefreshTokenCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dent1.Data.Entities.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PermissionId", "Effect")
                        .IsUnique();

                    b.ToTable("UserPermissionOverrides");
                });

            modelBuilder.Entity("Dent1.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("Dent1.Data.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dent1.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
